### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by FedeGueli**
Corrected the un-aliased pango lineage that was missing a .1

### CODE REVIEW

**Comment by Over-There-Is** [comment]
KV.1	Alias of B.1.1.529.2.86.1.1.4.5.1, S:S680F, after C28948T, A2356T

**Comment by Over-There-Is** [comment]
There are two S:S680F branches on JN.1.4.5+C28948T branch, one with A2356T and one without.

**Comment by FedeGueli** [comment]
> There are two S:S680F branches on JN.1.4.5+C28948T branch, one with A2356T and one without.

have you checked this one what is of the two?

**Comment by FedeGueli** [comment]
> > There are two S:S680F branches on JN.1.4.5+C28948T branch, one with A2356T and one without.
> 
> have you checked this one which is of the two?

ok checked this has 2356T re Pr ing it

**Comment by FedeGueli** [comment]
> after C28948T, A2356T

PRed : https://github.com/cov-lineages/pango-designation/pull/2537 the previous branch deleted.

**Pull request closed without merging**
