### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by Memorablea**

### CODE REVIEW

**Comment by Mydtlwn** [comment]
The alias should is B.1.1.529.2.86.1.1.4.8。Please fix this.

**Comment by Memorablea** [comment]
@AngieHinrichs

**Comment by Memorablea** [comment]
> 别名应为 B.1.1.529.2.86.1.1.4.8。请解决这个问题。

OK

**Comment by AngieHinrichs** [comment]
Thanks @Memorablea!

**Pull request merged**
