### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by Memorablea**

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
I see a milestone for EG.4.2 has been added to sars-cov-2-variants/lineage-proposals, so @aviczhl2 if you are planning to also search that repo's milestones in your notebook, is the format of this edit compatible with what you will be looking for?

**Comment by aviczhl2** [comment]
> I see a milestone for EG.4.2 has been added to sars-cov-2-variants/lineage-proposals, so @aviczhl2 if you are planning to also search that repo's milestones in your notebook, is the format of this edit compatible with what you will be looking for?

Yeah I can do that.

**Comment by aviczhl2** [comment]
This lineage is included in the updated auto-ref #2118, so @AngieHinrichs pls accept #2118 and ignore this issue.

**Comment by AngieHinrichs** [comment]
Great, I see the corresponding addition in #2118, so I will close this one.  Thanks @Memorablea and @aviczhl2!

**Pull request closed without merging**
