### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by Memorablea**

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
> No description provided.

@Memorablea please provide a brief description of the changes, it is helpful for tracking.  (In my opinion it would be even better to put the brief description in the commit comment, it would be much more informative than "Update lineages_notes.txt".)

It looks like this change only removes the reference to Hubei.  Can you explain why that is necessary?  Thanks!

**Comment by Memorablea** [comment]
> > No description provided.
> 
> @Memorablea please provide a brief description of the changes, it is helpful for tracking. (In my opinion it would be even better to put the brief description in the commit comment, it would be much more informative than "Update lineages_notes.txt".)
> 
> It looks like this change only removes the reference to Hubei. Can you explain why that is necessary? Thanks!

As is well known, the sequence upload speed in China is relatively slow, and there are very few provinces where it can be uploaded. In fact, when Hubei Province uploads, it often means that many provinces have also discovered this lineage.

**Comment by AngieHinrichs** [comment]
> As is well known, the sequence upload speed in China is relatively slow, and there are very few provinces where it can be uploaded. In fact, when Hubei Province uploads, it often means that many provinces have also discovered this lineage.

OK, thanks for explaining.  @corneliusroemer do you agree that Hubei should be de-emphasized (or at least treated as wait-and-see)?

**Comment by corneliusroemer** [comment]
Changes are fine with me, these geographic references are not essential and only serve to help distinguish lineages in case of errors. They are not intended to "blame" regions or suggest that the areas are the first or only where a lineage was sequenced.

It's true that I don't recall seeing sequences from too many provinces, thanks for pointing that out @Memorablea.

**Pull request merged**
