### PR TITLE
Fix LW.1.2，LF.8.1.1 Alias

### PR DESCRIPTION
**Pull request by Mydtlwn**

### CODE REVIEW

**Comment by DailyCovidCases** [comment]
I found something incorrect here:
https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt
Screenshot (269)
Correction: 
LF.8	        Alias of B.1.1.529.2.86.1.1.16.1.8, S:M153I, C3244T, A18432T, C27110T
LF.8.1	Alias of B.1.1.529.2.86.1.1.16.1.8.1, S:S31F
LF.8.1.1	Alias of B.1.1.529.2.86.1.1.16.1.8.1.1, S:T22N
ND.1	Alias of B.1.1.529.2.86.1.1.16.1.8.1.1.1, ORF1a:L4391F
ND.1.1	Alias of B.1.1.529.2.86.1.1.16.1.8.1.1.1.1, S:K478T
ND.2	Alias of B.1.1.529.2.86.1.1.16.1.8.1.1.2, S:K478E
ND.3	Alias of B.1.1.529.2.86.1.1.16.1.8.1.1.3, S:K478I

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by Mydtlwn** [comment]
@corneliusroemer

**Comment by Mydtlwn** [comment]
The long-unfixed Alias Bug has led to more Alias Bugs involving LW.1.2, LF.8.1.1, and the ND family, with a duration spanning from August to October.

**Comment by Mydtlwn** [comment]
@xz-keg

**Comment by Mydtlwn** [comment]
I suggest fixing the bug directly on the main branch after reviewing the files, as this bug already encompasses alias errors across the entire LW.1.2 and LF.8.1.1 families.

**Comment by Mydtlwn** [comment]
The error in LW.1.2 lies in writing the last digit of the alias as '.1', while the error in LF.8.1.1 and subsequent versions is missing a '.1'. Such minor errors are prone to occur in lineages like '.1.1.1'.

**Comment by Mydtlwn** [comment]
DailyCovidCases

**Comment by Mydtlwn** [comment]
@DailyCovidCases

**Comment by DailyCovidCases** [comment]
> @DailyCovidCases
Go to this web: https://github.com/cov-lineages/pango-designation/pull/2807

**Comment by Mydtlwn** [comment]
In your request #2807, please click on the 'Resolve Conflict' button. Check my file to see what differences there are compared to yours, and make the necessary changes accordingly. Once it's approved on that end, I can close it here.

**Comment by FedeGueli** [comment]
i have proposed one only PR encompassing all typos to be corrected : https://github.com/cov-lineages/pango-designation/pull/2808  you can close this one.

**Pull request closed without merging**
