### PR TITLE
Add 4 autoref from main page and 31 from lineage-proposals

### PR DESCRIPTION
**Pull request by aviczhl2**
Also modified the code to priortize milestones on main page.

@AngieHinrichs 
 If there's a milestone on both main page and sars-cov-2, it will prioritize main page now.

@ciscorucinski 
Please take a look at the new code now, may be helpful.

### CODE REVIEW

**Comment by FedeGueli** [comment]
> Also modified the code to priortize milestones on main page.
> 
> @AngieHinrichs If there's a milestone on both main page and sars-cov-2, it will prioritize main page now.
> 
> @ciscorucinski Please take a look at the new code now, may be helpful.

Thank you. so i can add all the milestones in the secondary page without fearing to mess things right?

**Comment by ciscorucinski** [comment]
I can't really see the diff for `automated-issue-ref.ipynb`. Notebook diffs are not supported well on GitHub it seems like. However, in `lineage_notes.txt`, there are some differences between what this PR suggests for linked issues and what @FedeGueli has suggested in his PRs.

**Comment by FedeGueli** [comment]
> I can't really see the diff for `automated-issue-ref.ipynb`. Notebook diffs are not supported well on GitHub it seems like. However, in `lineage_notes.txt`, there are some differences between what this PR suggests for linked issues and what @FedeGueli has suggested in his PRs.

Maybe for the fact i added milestones to secondary page ?

**Comment by aviczhl2** [comment]
> Thank you. so i can add all the milestones in the secondary page without fearing to mess things right?

If there's a milestone on main page, milestones on the secondary page won't influence the result. 
However it will take milestones from secondary pages if there's no milestone on main page.

**Comment by ciscorucinski** [comment]
> If there's a milestone on main page, milestones on the secondary page won't influence the result.

Not quite. This is happening within some lineages within this PR.

There are 4 lineages that convert his `cov-lineage/pango-designation` issue to a `sars-cov-2-variants/lineage-proposals` issue. And there is one lineage where it converts his 'sars-cov-2-variants/lineage-proposals' issue to a different 'sars-cov-2-variants/lineage-proposals' issue

This is the same issue I discovered earlier this week with auto generating this. It's why I am changing direction.

**Comment by ciscorucinski** [comment]
I believe that he shouldn't have to worry at all about milestoning issues. In fact, I think he should be encouraged to milestone every single connection; worry-free. 

@FedeGueli I am working on a new workflow that I hope to PR here soon. It will collect ALL lineage-milestone-issue connections and document them rather than needing to narrow it down to just one issue as with `lineage_notes.txt`. 

I plan on creating a supplementary file to go along with `lineage_notes.txt`. You can check out my repo's [mapping.json](https://github.com/ciscorucinski/pango-designation/blob/e3c2bc445c7fde5b4ed6126cfedded18c4aa1e6c/scripts/issue-milestone-check/mappings.json) file, which can be updated daily. The existing JSON file will be used for verification purposes anyways with my new workflow, and a simple JSON to table transformation could be applied to create this supplementary file. It might look possibly something like the following...

| Lineage  | Milestone | Issues | Repository                            |
| -------- | --------- | ------ | ------------------------------------- |
| ... | | | |
| EG.5.1.3 | 24        | 222    | sars-cov-2-variants/lineage-proposals |
| EG.5.1.4 | 801       | 2117   | cov-lineages/pango-designation        |
| EG.5.1.4 | 18        | 428    | sars-cov-2-variants/lineage-proposals |
| ... | | | |

With this supplementary file, there will be no lost information; The only way to lose information is to not milestone and label enough.

**Comment by aviczhl2** [comment]
> Not quite. The opposite is happening within some lineages within this PR.
> 
> There are 5 lineages that convert his `cov-lineage/pango-designation` issue to a `sars-cov-2-variants/lineage-proposals` issue. And there is one lineage where it converts his `sars-cov-2-variants/lineage-proposals` issue to a different `sars-cov-2-variants/lineage-proposals` issue
> 
> This is the same issue I discovered earlier this week with auto generating this. It's why I am changing direction.

What are they? Each autoref shall not have any prior refs in lineage_notes.txt.  So such conversion won't happen.

**Comment by ciscorucinski** [comment]
I was not talking about that aspect.

Based on @FedeGueli 's PR and your PR, there are 5 lineages that have issues within the main repo where your PR didn't use those main repo issues, but the secondary repos issues.

The reason is because the main repo hasn't had it's milestones updated in 2 days. So they aren't milestoned yet, but @FedeGueli had identified these currently non-milestoned issues. The major issue is that since autoref does not modify existing references, all of these need to be correctly identified and fixed after each autoref update.

However, if autoref were to update existing references, then that would have it's own problems. This is why I'm focused on validation now

The following have been identified within the main repo...
- `HC.2`
- `HK.3.1`
- `JF.1`
- `XBB.1.16.23`
- `GE.1.3`

**Comment by aviczhl2** [comment]
> The following have been identified within the main repo...
> 
> * `HC.2`
> * `HK.3.1`
> * `JF.1`
> * `XBB.1.16.23`
> * `GE.1.3`

I see. In the next version I'll come up with a fix of this.

 Currently autorefs and manual refs are actually distinguishable (manual refs use “from" while autoref uses "From"), so it's not hard to detect and remove autorefs and update with new ones.

**Comment by ciscorucinski** [comment]
Ah sorry, it was the PR from @Over-There-Is, not @FedeGueli. Maybe that led to some confusion.

> Assuming they eventually get their milestones on main page they eventually will be linked to their main page ref.

This will be good,. This sounds like that autoref will be changed to overwrite existing references, right? 
 
> manual refs use “from" while autoref uses "From")

This isn't currently consistent within `lineage_notes.txt`, though. There are PRs that have already "corrected" some references that use `From` to use `from` instead. There are at least 4 examples of this in @Over-There-Is 's current PR.

**Comment by AngieHinrichs** [comment]
Thanks @aviczhl2!  I had to manually resolve some conflicts, and there was a warning that I would be changing a master branch (probably yours since this still requires merging) -- so you might want to check your local master branch vs. github.  I hope that doesn't create an inconvenience for you.

**Pull request merged**
