### PR TITLE
Lineage notes standardization

### PR DESCRIPTION
**Pull request by ciscorucinski**
Source: #2280 (@RaphaelRaphael)

This PR should make it easier to view the existing changes and to allow for easier communication.

- [x] ( A ) Reinstate `sars-cov-2-variants/lineage-proposals` changes
- [x] ( B ) Determine standardized issue label format
- [x] ( C ) Reinstate `From`/ `from` differences
- [x] ( D ) Fix issue label formats based on ( B )
- [x] ( E ) Fix `Alias of` issues
- [x] ( F ) Fix `xUSA` replacement issues
- [x]  ( G ) Fix missing comma before issue label
- [x] ( H ) Fix issue labels not being last

@aviczhl2 I definitely need your input on ( B ) and ( C ) due to AutoRef. 
CC @AngieHinrichs

### CODE REVIEW

**Comment by ciscorucinski** [comment]
( B ) Standardized Issue Label Format

Here are some suggestions. Currently we do both `A` and `B` along with a few others. 
| A | B | C |
| :---: | :---: | :---: |
| `cov-lineages/pango-designation#xxx`<br>`sars-cov-2-variants/lineage-proposals#xxx` | `from pango-designation issue #xxx`<br>`from lineage-proposals issue #xxx` | Something else? |

`A` is my choice

**Comment by ciscorucinski** [comment]
When fixing ( G ), I discovered the usage of non-standard commas (`，`). It is a single symbol that combines a comma and a space. 

While the browsers Find functionality can locate this non-standard comma via the usage of a standard comma, Regex appears not able to parse the non-standard comma via the usage of a standard comma. [Regex parse example](https://regex101.com/r/rHh3FU/1).

**Comment by ciscorucinski** [comment]
I committed the following standard. However, I can still be changed very easily now.

I am doing an asymmetric standard where the main repo will be given the format `#xxx`. The secondary repo will be given the format `sars-cov-2-variants/lineage-proposals#xxx`

This makes it slightly easier to distinguish between repos within lineage_notes. It is also the same format that AutoRef is using (as far as I am aware).

**Comment by ciscorucinski** [comment]
@AngieHinrichs the JSON Check is passing now. Also, if this PR isn't wanted then it can be closed

**Comment by AngieHinrichs** [comment]
Thanks for all your work on this @ciscorucinski, and sorry it took me a while to give it a proper look.  The non-standard comma character is 🤯 , I will look out for that in future PRs.  And I agree with your choice of asymmetric issue number formatting.

**Pull request merged**
