### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by FedeGueli**
Corrected the reference-issue

### CODE REVIEW

**Comment by ciscorucinski** [comment]
I wonder if we should just attach the same milestone to the duplicate issues

(1) Right now only #2203 indicates it's been designated and milestoned. #2071 makes no reference to either of those two concepts. There is no direct reference to the designation given.

(2) For adding issues to lineage_notes, we are in the process of automating the collection of related PANGO lineages, issues, and milestones...

However, without #2071 being milestoned, only #2203 will be discovered automatically. If both are milestoned, then both can be discovered. Without milestoning both issues, then the future automatic process will end up reverting this commit back to #2203

**Comment by AngieHinrichs** [comment]
> I wonder if we should just attach the same milestone to the duplicate issues
> ...
> ... Without milestoning both issues, then the future automatic process will end up reverting this commit back to https://github.com/cov-lineages/pango-designation/issues/2203

Good point @ciscorucinski, although depending on how it's implemented, I think it might just append " From #2203", so this would say "... from #2071 From #2203" -- @aviczhl2 your notebook code appends if it doesn't see the issue number, it doesn't remove anything, right?

In the meantime, IIRC @aviczhl2's notebook ignores milestones that don't have exactly one issue, so associating two issues with the same milestone would exclude the milestone.  But of course that code could be changed to support multiple issues if desired.  @ciscorucinski since you already have the query that associates issues with milestones, can you search the resulting JSON to find which milestones (if any) already have multiple issues?

**Comment by ciscorucinski** [comment]
```
{
  "number": 4,
  "title": "B.1.526",
  "issue": "6, 45"
}
{
  "number": 20,
  "title": "B.1.617",
  "issue": "38, 49"
}
{
  "number": 30,
  "title": "AT.1",
  "issue": "47, 152"
}
{
  "number": 31,
  "title": "B.1.619",
  "issue": "44, 149"
}
{
  "number": 61,
  "title": "B.1.626",
  "issue": "118, 136"
}
{
  "number": 62,
  "title": "B.1.617.2",
  "issue": "113, 135"
}
{
  "number": 119,
  "title": "AY.33",
  "issue": "215, 219"
}
{
  "number": 282,
  "title": "BA.2.38",
  "issue": "541, 581, 582"
}
{
  "number": 690,
  "title": "XBY",
  "issue": "1653, 1669"
}
```

**Comment by AngieHinrichs** [comment]
Thanks @ciscorucinski!  I will look at those issues to make sure they're all relevant to the lineages named in the milestones.  (I expect they all will be, just want to check.)

**Comment by AngieHinrichs** [comment]
While the issues are all relevant to the milestone lineages (no surprise), their relationship are not always the same.  Sometimes the issues are duplicate proposals; other times there is both a proposal issue and a correction issue; and in the case of B.1.617.2, both linked issues are corrections/additions of more designated sequences.

I see no harm in linking all those issues, though they're not necessarily issue proposals (which is a safer assumption when only one issue is associated).

**Comment by aviczhl2** [comment]
> your notebook code appends if it doesn't see the issue number, it doesn't remove anything, right?

Yes of course. If there's already a reference the autoref will do nothing. It won't remove or try to update existing refs. So for such extreme cases we can do safe manual fix.

**Comment by aviczhl2** [comment]
> However, without #2071 being milestoned, only #2203 will be discovered automatically. If both are milestoned, then both can be discovered. Without milestoning both issues, then the future automatic process will end up reverting this commit back to #2203

If there's already a reference the autoref will do nothing. It won't remove or try to update existing refs. Also, if you manually fixed something it won't try to update that again.

**Comment by AngieHinrichs** [comment]
I'll accept this PR (thanks @FedeGueli!) and leave the matter of support for multi-issue milestones as possible future work by others.  🙂  I added milestone JD.1 to #2071.

**Comment by FedeGueli** [comment]
> I'll accept this PR (thanks @FedeGueli!) and leave the matter of support for multi-issue milestones as possible future work by others. 🙂 I added milestone JD.1 to #2071.

Thx you all!

**Pull request merged**
