### PR TITLE
Update lineage_notes.txt

### PR DESCRIPTION
**Pull request by NkRMnZr**
FL*/EG* corrections; replace further mutations like `T478R` or `K478R` to unified/most common `478R`

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
Thanks for the corrections.  Is there consensus from the group about removing the "from" allele (like T or K in T478R or K478R) and keeping only the "to" allele (R)?  I guess missing information can't be incorrect, but sometimes it is interesting to keep track of multiple successive changes.  @corneliusroemer @FedeGueli @aviczhl2 @ciscorucinski @Over-There-Is @HynnSpylor @Memorablea ?

**Comment by FedeGueli** [comment]
> Thanks for the corrections. Is there consensus from the group about removing the "from" allele (like T or K in T478R or K478R) and keeping only the "to" allele (R)? I guess missing information can't be incorrect, but sometimes it is interesting to keep track of multiple successive changes. @corneliusroemer @FedeGueli @aviczhl2 @ciscorucinski @Over-There-Is @HynnSpylor @Memorablea ?

I prefer always wild type to actual mutation as S:G339 S:V445A it leaves without doubt. I spoke with Ryan many months ago but we didnt end with a way or another.

**Comment by Memorablea** [comment]
> I think this should be related/addition to the Lineage Notes Standardization PR #2283 to keep multi-step mutations well informed and in a unified manner.
> 
> There are a few options:
> 
> * Keep it strict to  reference, eg.  (✔️fits most places with a query ❌ does not show the mutation history)`Lineage B/wildtype``S:T478R`
> * Keep it to nearest phylogenetic ancestor as reference, eg.  (✔️ shows part of the mutation history ❌ does not fit query on certain places like GISAID; causing confusions especially multi-step mutations)`S:K478R`
> * Using what is most common in lineage_notes, which omitted the original aa, eg.  (✔️ most clear without any confusions ❌ does not fit query; does not show the mutation history)`S:478R`
> * Or, any other way that can satisfy both criteria: showing the AA changes/transitions while  searchable (ie. if writing it as  which shows the 2-step mutations from WT to Omicron then to certain XBB lineages, however it does not seem to be _search-friendly_ to `CTRL+F``S:T478K>R``478R`)
> 
> I had a chat with @HynnSpylor on this topic on another PR before ( #2139 , obsoleted so retracted) and I have no problem with it then, but now we are having lineages like [sars-cov-2-variants/lineage-proposals#961](https://github.com/sars-cov-2-variants/lineage-proposals/issues/961) and potentially even more with multi-step mutations in the future, so maybe it's time to regulate it to a proper format.

agree

**Comment by HynnSpylor** [comment]
Sorry for a late reply!
Now I prefer to the WT-latest mutation (e.g. S:T478R for XBB.1.16*, E484K for BA.2.86*) for the proper format (used in the defining of a lineage). The "intermediate" mutation (like S:K478R)  can be used for detail description (with the previous mutations or the whole pathway).

**Pull request closed without merging**
